version: "3"
services:
    vizsgaremek-app:
        container_name: vizsgaremek
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
          - .:/app
          - app/node_modules          
        ports:
          - 3000:3000